### ISSUE TITLE
Record some test cases to use for speech to text recognizer

### ISSUE THREAD

**Issue by ByteOfKathy** [ByteOfKathy/manuela#9]
### Part 1
- [x] create a live speech to text recognizer
- [x] successfully recognize speech from a mic
- [x] Output the speech as text
### Part 2
- [ ] Record some speech test cases
- [ ] Have Manuela respond accordingly
### Part 3
- [ ] Grab some pictures for testing
- [ ] Have Manuela respond accordingly
### Finale
- [ ] Have Manuela respond accordingly to live input (camera + voice)
- suggestion to add a debug flag to print what the speech to text detects.
